# Site settings
title: NobeWP
header-img: img/hello-world.jpg
email: 784932580@qq.com
description: "JUST DO IT "
baseurl: ""
url: ""
twitter_username: 
github_username:  nobewp
facebook_username:  
weibo_username: 
zhihu_username: 

# Build settings
markdown: kramdown 

# markdown: redcarpet
# redcarpet can auto highlight code, but the lack of header-id make the catalog impossible 

highlighter: pygments
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

# use Github Flavored Markdown !important
# document: http://jekyllrb.com/docs/configuration/#kramdown

kramdown:
  input: GFM
